Repository bsdpot/pot, pull requests merged in 2022-01, with the labels that each got.

#196 Inherit encryption property from parent filesystem
  CHANGELOG.md
  share/pot/common.sh
  share/pot/create.sh
  share/pot/import.sh
Labels: feature

#197 Get rss fix zfs crash
  CHANGELOG.md
  share/pot/get-rss.sh
  tests/get-rss1.sh
Labels: bug

#198 No spaces in mountpoints
  CHANGELOG.md
  share/pot/common.sh
  share/pot/mount-in.sh
  tests/common8.sh
  tests/mount-in1.sh
Labels: enhancement
